package com.rationalteam.rtreadymix;

public interface IRationalEvents {
    public String RTEVENT_NEWORDER="RTEVENT_NEWORDER";
    public String RTEVENT_ORDER_MODIFIED="RTEVENT_ORDER_MODIFIED";
    public String RTEVENT_ORDER_PRICED="RTEVENT_ORDER_PRICED";
    public String RTEVENT_ORDER_CANCELED="RTEVENT_ORDER_CANCELED";
    public String RTEVENT_CLIENT_EVENT="RTEVENT_CLIENT_EVENT";
    public String RTEVENT_PASSWORD_RESET="RTEVENT_PASSWORD_RESET";
}
